"""Advanced task management: subtasks, recurrence, snoozing, bulk edits.

Sits beside `EntryService` rather than inside it. `EntryService` answers "what is
this thing and what does it say"; this one answers "what do I have to do about
it and when". Merging them would produce one class where every task-specific
concern has to be guarded by `if entry_type == TASK`, which is how a service
grows to a thousand lines nobody wants to touch.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta

from sqlalchemy import Select, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain import recurrence
from app.domain.enums import (
    ActivityAction,
    EntryOrigin,
    EntryStatus,
    EntryType,
    Priority,
)
from app.domain.errors import NotFoundError, ValidationError
from app.infra.db.models.core import Entry, Subtask, Task
from app.observability import metrics
from app.observability.logging import get_logger
from app.services.activity_service import ActivityService
from app.services.identity_service import Principal

log = get_logger("task")

# Sparse ordering: a reorder rewrites one row instead of the whole list.
POSITION_STEP = 100
# Below this gap two neighbours can no longer be separated and the list is
# renumbered. Rare enough to be worth the simplicity of the sparse scheme.
MIN_GAP = 2
MAX_SUBTASKS = 100
MAX_BULK = 200


@dataclass(slots=True)
class CompletionResult:
    entry: Entry
    # The occurrence generated by completing a recurring task, if any. Returned
    # rather than merely created so the interface can say "next: Monday" at the
    # moment of completion, which is when the user is looking.
    next_occurrence: Entry | None = None


class TaskService:
    def __init__(self, session: AsyncSession, *, principal: Principal) -> None:
        self._session = session
        self._principal = principal
        self._activity = ActivityService(session, principal=principal)

    # -- lookup -------------------------------------------------------------
    async def _entry(self, entry_id: uuid.UUID) -> Entry:
        entry = (
            await self._session.execute(
                select(Entry).where(Entry.id == entry_id, Entry.deleted_at.is_(None))
            )
        ).scalar_one_or_none()
        if entry is None:
            raise NotFoundError(f"Entrée {entry_id} introuvable.")
        return entry

    async def _task(self, entry: Entry) -> Task:
        task = await self._session.get(Task, entry.id)
        if task is None:
            if EntryType(entry.entry_type) is not EntryType.TASK:
                raise ValidationError("Cette action ne s'applique qu'aux tâches.")
            task = Task(entry_id=entry.id, account_id=entry.account_id)
            self._session.add(task)
            await self._session.flush()
        return task

    # -- subtasks -----------------------------------------------------------
    async def list_subtasks(self, entry_id: uuid.UUID) -> list[Subtask]:
        result = await self._session.execute(
            select(Subtask).where(Subtask.entry_id == entry_id).order_by(Subtask.position)
        )
        return list(result.scalars().all())

    async def add_subtask(
        self, entry_id: uuid.UUID, *, title: str, origin: EntryOrigin = EntryOrigin.USER
    ) -> Subtask:
        entry = await self._entry(entry_id)
        clean = title.strip()
        if not clean:
            raise ValidationError("Le titre d'une sous-tâche ne peut pas être vide.", field="title")

        count = int(
            (
                await self._session.execute(
                    select(func.count()).select_from(Subtask).where(Subtask.entry_id == entry_id)
                )
            ).scalar_one()
        )
        if count >= MAX_SUBTASKS:
            # A checklist this long is a project. Saying so beats letting the
            # interface degrade silently at 400 rows.
            raise ValidationError(
                f"Une tâche ne peut pas dépasser {MAX_SUBTASKS} sous-tâches. "
                "Au-delà, créez un projet.",
                field="subtasks",
            )

        last = (
            await self._session.execute(
                select(func.max(Subtask.position)).where(Subtask.entry_id == entry_id)
            )
        ).scalar_one_or_none()

        subtask = Subtask(
            id=uuid.uuid4(),
            account_id=self._principal.account_id,
            entry_id=entry_id,
            title=clean[:300],
            position=(int(last) if last is not None else 0) + POSITION_STEP,
            origin=origin,
        )
        self._session.add(subtask)
        self._activity.record(
            ActivityAction.SUBTASK_ADDED,
            entry_id=entry_id,
            label=entry.title,
            detail={"title": clean[:120]},
        )
        await self._session.flush()
        return subtask

    async def update_subtask(
        self,
        subtask_id: uuid.UUID,
        *,
        title: str | None = None,
        completed: bool | None = None,
    ) -> Subtask:
        subtask = await self._session.get(Subtask, subtask_id)
        if subtask is None:
            raise NotFoundError(f"Sous-tâche {subtask_id} introuvable.")

        if title is not None:
            clean = title.strip()
            if not clean:
                raise ValidationError("Le titre ne peut pas être vide.", field="title")
            subtask.title = clean[:300]

        if completed is not None:
            was_done = subtask.completed_at is not None
            subtask.completed_at = datetime.now(UTC) if completed else None
            if completed and not was_done:
                entry = await self._entry(subtask.entry_id)
                self._activity.record(
                    ActivityAction.SUBTASK_COMPLETED,
                    entry_id=subtask.entry_id,
                    label=entry.title,
                    detail={"title": subtask.title[:120]},
                )
        await self._session.flush()
        return subtask

    async def delete_subtask(self, subtask_id: uuid.UUID) -> None:
        subtask = await self._session.get(Subtask, subtask_id)
        if subtask is None:
            raise NotFoundError(f"Sous-tâche {subtask_id} introuvable.")
        await self._session.delete(subtask)
        await self._session.flush()

    async def reorder_subtasks(
        self, entry_id: uuid.UUID, ordered_ids: list[uuid.UUID]
    ) -> list[Subtask]:
        """Apply an explicit order.

        Takes the full ordered list rather than a (from, to) pair: drag-and-drop
        on a flaky connection produces out-of-order deltas, and replaying two of
        them against a shared list gives an order nobody asked for. Sending the
        result the user is looking at is idempotent.
        """
        subtasks = await self.list_subtasks(entry_id)
        by_id = {subtask.id: subtask for subtask in subtasks}
        unknown = [str(item) for item in ordered_ids if item not in by_id]
        if unknown:
            raise ValidationError(
                f"Sous-tâches inconnues : {', '.join(unknown[:3])}", field="order"
            )

        position = POSITION_STEP
        for subtask_id in ordered_ids:
            by_id[subtask_id].position = position
            position += POSITION_STEP
        # Anything the client did not mention keeps its relative order at the end
        # rather than vanishing from the list.
        for subtask in subtasks:
            if subtask.id not in set(ordered_ids):
                subtask.position = position
                position += POSITION_STEP

        await self._session.flush()
        return await self.list_subtasks(entry_id)

    async def subtask_progress(
        self, entry_ids: list[uuid.UUID]
    ) -> dict[uuid.UUID, tuple[int, int]]:
        """(done, total) per entry, in one query.

        Batched because the list screen shows progress on every row: doing it per
        row is the classic N+1 that makes a list of fifty tasks issue fifty-one
        queries.
        """
        if not entry_ids:
            return {}
        result = await self._session.execute(
            select(
                Subtask.entry_id,
                func.count().label("total"),
                func.count(Subtask.completed_at).label("done"),
            )
            .where(Subtask.entry_id.in_(entry_ids))
            .group_by(Subtask.entry_id)
        )
        return {row.entry_id: (int(row.done), int(row.total)) for row in result.all()}

    # -- lifecycle ----------------------------------------------------------
    async def complete(self, entry_id: uuid.UUID) -> CompletionResult:
        """Complete a task and, if it recurs, create the next occurrence."""
        entry = await self._entry(entry_id)
        if EntryType(entry.entry_type) is not EntryType.TASK:
            raise ValidationError("Seule une tâche peut être terminée.")

        task = await self._task(entry)
        now = datetime.now(UTC)
        task.completed_at = now
        entry.status = EntryStatus.DONE
        self._activity.record(ActivityAction.COMPLETED, entry_id=entry.id, label=entry.title)
        metrics.entries_completed_total.labels(entry.entry_type).inc()

        next_entry = await self._roll_forward(entry, task, now)
        await self._session.flush()
        return CompletionResult(entry=entry, next_occurrence=next_entry)

    async def _roll_forward(self, entry: Entry, task: Task, now: datetime) -> Entry | None:
        """Create the occurrence that follows a completed recurring task.

        The next date is computed from the *previous due date*, not from now: a
        Monday task completed on Wednesday is still due next Monday. Anchoring on
        completion makes the schedule drift a little every week until it means
        nothing (see `domain.recurrence`).
        """
        if not task.recurrence_rule or task.due_at is None:
            return None

        next_due = recurrence.next_occurrence(
            task.recurrence_rule,
            previous_due=task.due_at,
            now=now,
            timezone=self._principal.timezone,
            occurrences_so_far=task.recurrence_count + 1,
        )
        if next_due is None:
            return None

        next_entry = Entry(
            id=uuid.uuid4(),
            account_id=entry.account_id,
            user_id=entry.user_id,
            project_id=entry.project_id,
            # Not linked to the capture: the audio documents the first occurrence,
            # not the twentieth. Keeping the link would make one recording look
            # like the source of a hundred tasks.
            capture_id=None,
            entry_type=EntryType.TASK,
            title=entry.title,
            body=entry.body,
            status=EntryStatus.ACTIVE,
            occurred_at=now,
            origin=EntryOrigin.TRANSFORM,
            edited_by_user_at=now,
        )
        self._session.add(next_entry)
        await self._session.flush()

        self._session.add(
            Task(
                entry_id=next_entry.id,
                account_id=entry.account_id,
                due_at=next_due,
                due_precision=task.due_precision,
                due_raw_expression=task.due_raw_expression,
                priority=task.priority,
                estimated_minutes=task.estimated_minutes,
                assignee_label=task.assignee_label,
                recurrence_rule=task.recurrence_rule,
                recurrence_count=task.recurrence_count + 1,
                recurred_from_entry_id=entry.id,
            )
        )
        self._activity.record(
            ActivityAction.RECURRED,
            entry_id=next_entry.id,
            label=entry.title,
            actor_type="system",
            detail={"previous_entry_id": str(entry.id), "due_at": next_due.isoformat()},
        )
        await self._session.flush()
        log.info(
            "task.recurred",
            entry_id=str(entry.id),
            next_entry_id=str(next_entry.id),
            due_at=next_due.isoformat(),
        )
        return next_entry

    async def reopen(self, entry_id: uuid.UUID) -> Entry:
        entry = await self._entry(entry_id)
        task = await self._session.get(Task, entry.id)
        if task is not None:
            task.completed_at = None
        entry.status = EntryStatus.ACTIVE
        self._activity.record(ActivityAction.REOPENED, entry_id=entry.id, label=entry.title)
        await self._session.flush()
        return entry

    async def snooze(self, entry_id: uuid.UUID, *, until: datetime) -> Entry:
        """Hide a task until a chosen moment.

        Snoozing does **not** move the due date. "I do not want to see this until
        Thursday" and "this is due Thursday" are different statements, and a tool
        that conflates them quietly rewrites the user's commitments.
        """
        if until <= datetime.now(UTC):
            raise ValidationError("La date de report doit être dans le futur.", field="until")
        entry = await self._entry(entry_id)
        task = await self._task(entry)
        task.snoozed_until = until
        entry.status = EntryStatus.SNOOZED
        self._activity.record(
            ActivityAction.SNOOZED,
            entry_id=entry.id,
            label=entry.title,
            detail={"until": until.isoformat()},
        )
        await self._session.flush()
        return entry

    async def unsnooze_due(self) -> int:
        """Wake tasks whose snooze has expired. Idempotent; run from the sweeper."""
        now = datetime.now(UTC)
        rows = await self._session.execute(
            select(Entry, Task)
            .join(Task, Task.entry_id == Entry.id)
            .where(
                Entry.status == EntryStatus.SNOOZED.value,
                Task.snoozed_until.isnot(None),
                Task.snoozed_until <= now,
                Entry.deleted_at.is_(None),
            )
        )
        woken = 0
        for entry, task in rows.all():
            entry.status = EntryStatus.ACTIVE
            task.snoozed_until = None
            woken += 1
        if woken:
            await self._session.flush()
        return woken

    async def set_priority(self, entry_id: uuid.UUID, priority: Priority) -> Entry:
        entry = await self._entry(entry_id)
        task = await self._task(entry)
        if task.priority != priority.value:
            self._activity.record(
                ActivityAction.PRIORITY_CHANGED,
                entry_id=entry.id,
                label=entry.title,
                detail={"from": task.priority, "to": priority.value},
            )
            task.priority = priority
        await self._session.flush()
        return entry

    async def reschedule(self, entry_id: uuid.UUID, *, due_at: datetime | None) -> Entry:
        entry = await self._entry(entry_id)
        task = await self._task(entry)
        previous = task.due_at
        task.due_at = due_at
        if due_at is not None and task.due_precision is None:
            task.due_precision = "minute"
        # An explicit date supersedes the spoken wording: keeping "jeudi" next to
        # a date the user has since dragged elsewhere is just misleading.
        task.due_raw_expression = None
        self._activity.record(
            ActivityAction.RESCHEDULED,
            entry_id=entry.id,
            label=entry.title,
            detail={
                "from": previous.isoformat() if previous else None,
                "to": due_at.isoformat() if due_at else None,
            },
        )
        await self._session.flush()
        return entry

    async def set_recurrence(self, entry_id: uuid.UUID, *, rule: str | None) -> Entry:
        entry = await self._entry(entry_id)
        task = await self._task(entry)
        if rule:
            parsed = recurrence.parse(rule)
            if parsed is None:
                raise ValidationError(
                    "Règle de récurrence non prise en charge.", field="recurrence_rule"
                )
            task.recurrence_rule = parsed.to_rrule()
        else:
            task.recurrence_rule = None
        await self._session.flush()
        return entry

    async def pin(self, entry_id: uuid.UUID, *, pinned: bool) -> Entry:
        entry = await self._entry(entry_id)
        entry.pinned_at = datetime.now(UTC) if pinned else None
        await self._session.flush()
        return entry

    # -- bulk ---------------------------------------------------------------
    async def bulk_update(
        self,
        entry_ids: list[uuid.UUID],
        *,
        status: EntryStatus | None = None,
        priority: Priority | None = None,
        project_id: uuid.UUID | None = None,
        clear_project: bool = False,
    ) -> int:
        """Apply one change to many entries.

        Loads the rows rather than issuing a bare `UPDATE ... WHERE id IN`: RLS
        already scopes the read, the timeline needs each title, and completing a
        recurring task in bulk must still roll it forward. A set-based update
        would be faster and would quietly skip all three.
        """
        if not entry_ids:
            return 0
        if len(entry_ids) > MAX_BULK:
            raise ValidationError(
                f"Au plus {MAX_BULK} éléments par opération groupée.", field="ids"
            )

        query: Select[tuple[Entry]] = select(Entry).where(
            Entry.id.in_(entry_ids), Entry.deleted_at.is_(None)
        )
        entries = list((await self._session.execute(query)).scalars().all())

        touched = 0
        for entry in entries:
            if status is not None and entry.status != status.value:
                if status is EntryStatus.DONE and EntryType(entry.entry_type) is EntryType.TASK:
                    await self.complete(entry.id)
                else:
                    entry.status = status
                    self._activity.record(
                        ActivityAction.EDITED,
                        entry_id=entry.id,
                        label=entry.title,
                        detail={"status": status.value},
                    )
                touched += 1
            if priority is not None:
                await self.set_priority(entry.id, priority)
                touched += 1
            if clear_project or project_id is not None:
                target = None if clear_project else project_id
                if entry.project_id != target:
                    entry.project_id = target
                    self._activity.record(
                        ActivityAction.PROJECT_CHANGED,
                        entry_id=entry.id,
                        label=entry.title,
                        project_id=target,
                    )
                    touched += 1

        if touched:
            await self._session.flush()
        return len(entries)

    # -- queries the planning screens need ----------------------------------
    async def overdue(self, *, limit: int = 50) -> list[tuple[Entry, Task]]:
        now = datetime.now(UTC)
        result = await self._session.execute(
            select(Entry, Task)
            .join(Task, Task.entry_id == Entry.id)
            .where(
                Entry.deleted_at.is_(None),
                Entry.status.notin_((EntryStatus.DONE.value, EntryStatus.ARCHIVED.value)),
                Task.completed_at.is_(None),
                Task.due_at.isnot(None),
                Task.due_at < now,
            )
            .order_by(Task.due_at.asc())
            .limit(limit)
        )
        return [(row[0], row[1]) for row in result.all()]

    async def in_range(
        self, *, start: datetime, end: datetime, include_done: bool = True
    ) -> list[tuple[Entry, Task]]:
        query = (
            select(Entry, Task)
            .join(Task, Task.entry_id == Entry.id)
            .where(
                Entry.deleted_at.is_(None),
                Task.due_at.isnot(None),
                Task.due_at >= start,
                Task.due_at < end,
            )
            .order_by(Task.due_at.asc())
        )
        if not include_done:
            query = query.where(Task.completed_at.is_(None))
        result = await self._session.execute(query)
        return [(row[0], row[1]) for row in result.all()]

    async def upcoming(self, *, days: int = 7, limit: int = 100) -> list[tuple[Entry, Task]]:
        now = datetime.now(UTC)
        rows = await self.in_range(start=now, end=now + timedelta(days=days), include_done=False)
        return rows[:limit]
