"""Static snapshot generation for the public demonstration site.

The application is local-first and has no authentication (ADR-001). Publishing
the API would expose read *and write* access to anyone with the URL, so the
public demo does not publish the API at all: this module records the responses
of every read endpoint the interface calls, for the demonstration profile only,
into a single JSON file the front end loads instead of making requests.

What that buys, and what it costs:

  - the published site is entirely static. No backend, no database, no
    credentials, no attack surface, and nothing of the owner's real data ever
    leaves the machine — the generator refuses to run against a profile that
    is not flagged as demo;
  - writes are impossible rather than merely discouraged, because there is
    nothing to write to;
  - the snapshot is a point in time. It is regenerated by a build step, and a
    stale one shows stale figures with no warning beyond its `generated_at`.

The canonical URL is the key, and both sides must agree on it exactly. Query
parameters are sorted here and sorted in the TypeScript client, because
`?limit=8&profile=demo` and `?profile=demo&limit=8` are the same request and
must not become two different cache entries.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import BusinessCase, Profile, TargetRole

# The levels the evidence view offers, and the scenarios the case view offers.
# Anything the interface can request must be recorded, or the static build
# shows an error where a view should be.
EVIDENCE_LEVELS = (2, 3, 4, 5)
SCENARIOS = ("base", "pessimistic", "optimistic")
QUARTERS_BACK = (1, 6, 8)
CRITICAL_PATH_LIMITS = (8, 10)


@dataclass(frozen=True)
class SnapshotResult:
    path: Path
    profile: str
    entries: int
    bytes_written: int
    failures: dict[str, int]


def canonical(path: str, params: dict[str, Any] | None = None) -> str:
    """Path plus sorted, non-empty query parameters.

    Mirrors `query()` in the TypeScript client. If the two ever disagree the
    front end asks for a key the snapshot does not hold, and says so by name
    rather than rendering an empty view.
    """
    if not params:
        return path
    pairs = [
        (key, str(value))
        for key, value in params.items()
        if value is not None and value != ""
    ]
    if not pairs:
        return path
    rendered = "&".join(f"{key}={value}" for key, value in sorted(pairs))
    return f"{path}?{rendered}"


def planned_requests(session: Session, profile_code: str) -> list[str]:
    """Every read the interface can issue against the demonstration profile."""
    p = {"profile": profile_code}
    requests: list[str] = [
        canonical("/health"),
        canonical("/meta"),
        canonical("/profiles"),
        canonical("/phases"),
        canonical("/target-roles"),
        canonical("/deliverable-types"),
        canonical("/skills/levels"),
        canonical("/skills/graph"),
        canonical("/postings"),
        canonical("/agent-runs"),
        canonical("/skills/positions", p),
        canonical("/skills/available", p),
        canonical("/skills/decayed", p),
        canonical("/skills/domains/summary", p),
        canonical("/skills/learning-order", p),
        canonical("/deliverables", p),
        canonical("/periodic-reviews", p),
        canonical("/cases", p),
        canonical("/market/gaps", p),
    ]

    for limit in CRITICAL_PATH_LIMITS:
        requests.append(canonical("/skills/critical-path", {**p, "limit": limit}))
    for back in QUARTERS_BACK:
        requests.append(canonical("/quota-status", {**p, "quarters_back": back}))
    for level in EVIDENCE_LEVELS:
        requests.append(canonical("/evidence-cv", {**p, "min_level": level}))

    for role in session.scalars(select(TargetRole)):
        requests.append(canonical("/market/gaps", {**p, "target_role": role.code}))

    profile = session.scalar(select(Profile).where(Profile.code == profile_code))
    cases = (
        session.scalars(select(BusinessCase).where(BusinessCase.profile_id == profile.id))
        if profile
        else []
    )
    for case in cases:
        for scenario in SCENARIOS:
            requests.append(canonical(f"/cases/{case.id}", {**p, "scenario": scenario}))
            requests.append(
                canonical(f"/cases/{case.id}/cause-tree", {**p, "scenario": scenario})
            )
            requests.append(canonical(f"/cases/{case.id}/roi", {**p, "scenario": scenario}))
        requests.append(canonical(f"/cases/{case.id}/roi/scenarios", p))
        requests.append(canonical(f"/cases/{case.id}/roi/tornado", p))
        requests.append(canonical(f"/cases/{case.id}/roi/fragility", p))
        requests.append(canonical(f"/cases/{case.id}/reviews", p))
        requests.append(canonical(f"/cases/{case.id}/audit", p))

    # Stable order so a regenerated snapshot produces a minimal diff.
    return sorted(set(requests))


def _redact(url: str, body: Any, profile_code: str) -> Any:
    """Remove every trace of profiles other than the one being published.

    Two reasons, and the second is the one that bites. Privacy: the owner's
    real profile should not appear in a public file even as a name. And
    correctness: the interface has a profile selector built from `/profiles`,
    so a visitor offered "Owner" could select it — and every subsequent
    request would be a key the snapshot does not hold, breaking every view.
    Filtering here means the selector can only offer what was recorded.
    """
    if url.startswith("/profiles") and isinstance(body, list):
        return [row for row in body if row.get("code") == profile_code]
    if url.startswith("/meta") and isinstance(body, dict):
        profiles = body.get("profiles")
        if isinstance(profiles, list):
            return {
                **body,
                "profiles": [row for row in profiles if row.get("code") == profile_code],
            }
    return body


def generate(
    session: Session,
    output: Path,
    profile_code: str = "demo",
) -> SnapshotResult:
    """Record every planned response into one JSON file.

    Refuses to run against a profile that is not flagged as demo. The whole
    point of this file is that it can be published, and publishing anything
    derived from the owner's real trajectory would defeat it — so the guard is
    here rather than in the caller, where it could be forgotten.
    """
    from fastapi.testclient import TestClient

    from app.db import get_db
    from app.main import app

    profile = session.scalar(select(Profile).where(Profile.code == profile_code))
    if profile is None:
        known = ", ".join(p.code for p in session.scalars(select(Profile)))
        raise ValueError(f"unknown profile '{profile_code}'. Known: {known}")
    if not profile.is_demo:
        raise ValueError(
            f"'{profile_code}' is not a demonstration profile. A snapshot is meant "
            "to be published, and this one holds real data."
        )

    def _override():  # noqa: ANN202
        yield session

    app.dependency_overrides[get_db] = _override
    responses: dict[str, Any] = {}
    failures: dict[str, int] = {}
    try:
        with TestClient(app) as client:
            for url in planned_requests(session, profile_code):
                reply = client.get(url)
                if reply.status_code != 200:
                    failures[url] = reply.status_code
                    continue
                responses[url] = _redact(url, reply.json(), profile_code)
    finally:
        app.dependency_overrides.pop(get_db, None)

    payload = {
        "generated_at": datetime.now(UTC).isoformat(),
        "profile": profile_code,
        "read_only": True,
        "responses": responses,
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    rendered = json.dumps(payload, ensure_ascii=False, separators=(",", ":"), default=str)
    output.write_text(rendered, encoding="utf-8")

    return SnapshotResult(
        path=output,
        profile=profile_code,
        entries=len(responses),
        bytes_written=len(rendered.encode("utf-8")),
        failures=failures,
    )
