"""SQLAlchemy models. Importing this package registers every table on Base.metadata."""

from app.infra.db.models.base import Base
from app.infra.db.models.core import (
    TENANT_TABLES,
    Account,
    AiRun,
    AppUser,
    AuditLog,
    Capture,
    CorrectionEvent,
    Device,
    Entry,
    EntryLink,
    EntryTag,
    JobRun,
    Outbox,
    Plan,
    Project,
    Subscription,
    Tag,
    Task,
    Transcript,
    TranscriptSegment,
    UsageCounter,
)

__all__ = [
    "TENANT_TABLES",
    "Account",
    "AiRun",
    "AppUser",
    "AuditLog",
    "Base",
    "Capture",
    "CorrectionEvent",
    "Device",
    "Entry",
    "EntryLink",
    "EntryTag",
    "JobRun",
    "Outbox",
    "Plan",
    "Project",
    "Subscription",
    "Tag",
    "Task",
    "Transcript",
    "TranscriptSegment",
    "UsageCounter",
]
