"""Tables for Phase 1 (Database.md §5).

Scope note: the semantic-search tables (`chunk`, embeddings) belong to sprint 06
in the Roadmap and are not part of this phase; the schema is otherwise faithful to
Database.md, including `account_id` on every tenant-owned table so RLS applies
uniformly (ADR-005).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import StrEnum
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Computed,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, TSVECTOR
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.domain.enums import (
    ActivityAction,
    AiOperation,
    AiRunStatus,
    CaptureKind,
    CaptureSource,
    CaptureStatus,
    DevicePlatform,
    EntryOrigin,
    EntryStatus,
    EntryType,
    NotificationKind,
    Priority,
    PushProvider,
    ReminderChannel,
    ReminderStatus,
)
from app.infra.db.models.base import Base, TimestampMixin, uuid_pk


def _enum_check(column: str, enum_cls: type[StrEnum]) -> CheckConstraint:
    values = ", ".join(f"'{member.value}'" for member in enum_cls)
    return CheckConstraint(f"{column} IN ({values})", name=f"{column}_valid")


# --------------------------------------------------------------------------- #
# Identity
# --------------------------------------------------------------------------- #
class Account(Base, TimestampMixin):
    __tablename__ = "account"

    id: Mapped[uuid.UUID] = uuid_pk()
    kind: Mapped[str] = mapped_column(
        String(16), default="personal", server_default="personal", nullable=False
    )
    display_name: Mapped[str | None] = mapped_column(String(120))
    data_region: Mapped[str] = mapped_column(
        String(8), default="eu", server_default="eu", nullable=False
    )
    status: Mapped[str] = mapped_column(
        String(24), default="active", server_default="active", nullable=False
    )
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        CheckConstraint("kind IN ('personal','team')", name="kind_valid"),
        CheckConstraint("data_region IN ('eu','us')", name="data_region_valid"),
        CheckConstraint(
            "status IN ('active','suspended','pending_deletion','deleted')",
            name="status_valid",
        ),
    )


class AppUser(Base, TimestampMixin):
    __tablename__ = "app_user"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    # Supabase `auth.users.id` — the external identity this row mirrors (ADR-029).
    auth_subject: Mapped[str] = mapped_column(String(255), nullable=False)
    email: Mapped[str] = mapped_column(String(320), nullable=False)
    email_verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    display_name: Mapped[str | None] = mapped_column(String(120))
    # Presentation data, but load-bearing: "jeudi" cannot be resolved without it.
    timezone: Mapped[str] = mapped_column(
        String(64), default="Europe/Paris", server_default="Europe/Paris", nullable=False
    )
    locale: Mapped[str] = mapped_column(
        String(8), default="fr-FR", server_default="fr-FR", nullable=False
    )
    role: Mapped[str] = mapped_column(
        String(16), default="owner", server_default="owner", nullable=False
    )
    daily_review_at: Mapped[str | None] = mapped_column(String(5))
    status: Mapped[str] = mapped_column(
        String(24), default="active", server_default="active", nullable=False
    )
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        UniqueConstraint("auth_subject", name="app_user_auth_subject_unique"),
        UniqueConstraint("email", name="app_user_email_unique"),
        CheckConstraint("role IN ('owner','admin','member')", name="role_valid"),
        CheckConstraint(
            "status IN ('active','suspended','pending_deletion','deleted')",
            name="status_valid",
        ),
    )


class Device(Base, TimestampMixin):
    __tablename__ = "device"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("app_user.id", ondelete="CASCADE"), nullable=False
    )
    # Stable per installation, generated by the client. The natural key for
    # "is this the same device?" — a push token is not, it rotates.
    install_id: Mapped[str] = mapped_column(String(64), nullable=False)
    platform: Mapped[str] = mapped_column(String(16), nullable=False)
    app_version: Mapped[str | None] = mapped_column(String(32))
    os_version: Mapped[str | None] = mapped_column(String(32))
    push_token: Mapped[str | None] = mapped_column(Text)
    # Which service delivers to this device (ADR-038). Stored rather than derived
    # from the platform: an Android phone and a Chrome tab both go through FCM,
    # and a Windows desktop is reachable by WNS or by a local toast depending on
    # how it was installed.
    push_provider: Mapped[str] = mapped_column(
        String(8), default=PushProvider.NONE, server_default="none", nullable=False
    )
    push_token_updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Set when the provider tells us the token is dead. Kept rather than deleted
    # so a device that re-registers is recognised instead of duplicated.
    push_failed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    push_failure_count: Mapped[int] = mapped_column(
        SmallInteger, default=0, server_default="0", nullable=False
    )
    name: Mapped[str | None] = mapped_column(String(80))
    last_seen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    sync_cursor: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        _enum_check("platform", DevicePlatform),
        _enum_check("push_provider", PushProvider),
        # One row per physical device: re-registering updates the token instead
        # of accumulating rows that all fire for the same phone.
        UniqueConstraint("user_id", "install_id", name="device_install_unique"),
        Index(
            "device_push_idx",
            "account_id",
            "push_provider",
            postgresql_where=revoked_at.is_(None),
        ),
    )


# --------------------------------------------------------------------------- #
# Capture
# --------------------------------------------------------------------------- #
class Capture(Base, TimestampMixin):
    __tablename__ = "capture"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("app_user.id", ondelete="RESTRICT"), nullable=False
    )
    device_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("device.id", ondelete="SET NULL")
    )

    # Idempotency key generated client-side before recording (ADR-009). Replaying
    # the declaration is a no-op, which is what makes offline retry safe.
    client_capture_id: Mapped[uuid.UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False)

    kind: Mapped[str] = mapped_column(
        String(16), default=CaptureKind.QUICK, server_default="quick", nullable=False
    )
    status: Mapped[str] = mapped_column(
        String(32),
        default=CaptureStatus.PENDING_UPLOAD,
        server_default="pending_upload",
        nullable=False,
    )

    audio_object_key: Mapped[str | None] = mapped_column(Text)
    audio_bytes: Mapped[int | None] = mapped_column(BigInteger)
    audio_format: Mapped[str | None] = mapped_column(String(16))
    audio_sample_rate: Mapped[int | None] = mapped_column(Integer)
    duration_ms: Mapped[int] = mapped_column(Integer, nullable=False)

    captured_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    capture_timezone: Mapped[str] = mapped_column(String(64), nullable=False)
    source: Mapped[str] = mapped_column(
        String(24), default=CaptureSource.APP, server_default="app", nullable=False
    )
    language_hint: Mapped[str | None] = mapped_column(String(8))

    processing_started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    processing_finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    failure_code: Mapped[str | None] = mapped_column(String(48))
    retry_count: Mapped[int] = mapped_column(
        SmallInteger, default=0, server_default="0", nullable=False
    )
    # Set when the plan quota is exceeded: the capture is still stored and
    # transcribed, only the AI enrichment is deferred (ADR-026).
    processing_mode: Mapped[str] = mapped_column(
        String(16), default="normal", server_default="normal", nullable=False
    )

    version: Mapped[int] = mapped_column(Integer, default=1, server_default="1", nullable=False)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    transcripts: Mapped[list[Transcript]] = relationship(
        back_populates="capture", cascade="all, delete-orphan", lazy="selectin"
    )

    __table_args__ = (
        UniqueConstraint("user_id", "client_capture_id", name="capture_client_id_unique"),
        CheckConstraint("duration_ms > 0", name="duration_positive"),
        CheckConstraint("audio_bytes IS NULL OR audio_bytes >= 0", name="bytes_positive"),
        CheckConstraint("processing_mode IN ('normal','degraded')", name="processing_mode_valid"),
        _enum_check("kind", CaptureKind),
        _enum_check("status", CaptureStatus),
        _enum_check("source", CaptureSource),
        CheckConstraint(
            "audio_format IS NULL OR audio_format IN ('m4a','opus','wav','mp3','webm')",
            name="audio_format_valid",
        ),
        Index("capture_account_time_idx", "account_id", captured_at.desc()),
        Index(
            "capture_processing_idx",
            "status",
            "created_at",
            postgresql_where=status.notin_(("completed", "abandoned")),
        ),
    )


class Transcript(Base):
    __tablename__ = "transcript"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    capture_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("capture.id", ondelete="CASCADE"), nullable=False
    )

    engine: Mapped[str] = mapped_column(String(48), nullable=False)
    engine_version: Mapped[str] = mapped_column(String(32), nullable=False)
    is_fallback: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="false", nullable=False
    )

    language: Mapped[str] = mapped_column(String(8), nullable=False)
    confidence: Mapped[float | None] = mapped_column(Numeric(4, 3))
    text: Mapped[str] = mapped_column(Text, nullable=False)
    word_count: Mapped[int] = mapped_column(Integer, default=0, server_default="0", nullable=False)
    words: Mapped[dict[str, Any] | None] = mapped_column(JSONB)

    # Immutable: a re-transcription creates a new revision, it never overwrites
    # (ADR-011).
    revision: Mapped[int] = mapped_column(
        SmallInteger, default=1, server_default="1", nullable=False
    )
    is_current: Mapped[bool] = mapped_column(
        Boolean, default=True, server_default="true", nullable=False
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    capture: Mapped[Capture] = relationship(back_populates="transcripts")

    __table_args__ = (
        CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="confidence_range",
        ),
        Index(
            "transcript_one_current_idx",
            "capture_id",
            unique=True,
            postgresql_where=is_current.is_(True),
        ),
    )


class TranscriptSegment(Base):
    __tablename__ = "transcript_segment"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    transcript_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("transcript.id", ondelete="CASCADE"), nullable=False
    )
    seq: Mapped[int] = mapped_column(Integer, nullable=False)
    start_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    end_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    speaker_label: Mapped[str | None] = mapped_column(String(32))
    text: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float | None] = mapped_column(Numeric(4, 3))

    __table_args__ = (
        CheckConstraint("end_ms > start_ms", name="segment_order"),
        CheckConstraint("start_ms >= 0", name="segment_start_positive"),
        UniqueConstraint("transcript_id", "seq", name="transcript_segment_seq_unique"),
    )


# --------------------------------------------------------------------------- #
# Knowledge
# --------------------------------------------------------------------------- #
class Project(Base, TimestampMixin):
    __tablename__ = "project"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    parent_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("project.id", ondelete="CASCADE")
    )
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    slug: Mapped[str] = mapped_column(String(140), nullable=False)
    color: Mapped[str | None] = mapped_column(String(7))
    icon: Mapped[str | None] = mapped_column(String(40))
    description: Mapped[str | None] = mapped_column(String(500))
    # Spoken aliases feed project matching during extraction (AI.md §5.2).
    aliases: Mapped[list[str]] = mapped_column(ARRAY(Text), server_default="{}", nullable=False)
    depth: Mapped[int] = mapped_column(SmallInteger, default=0, server_default="0", nullable=False)
    position: Mapped[int] = mapped_column(Integer, default=0, server_default="0", nullable=False)
    pinned_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    archived_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        UniqueConstraint("account_id", "slug", name="project_slug_unique"),
        CheckConstraint("depth BETWEEN 0 AND 2", name="depth_range"),
    )


class Tag(Base):
    __tablename__ = "tag"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    label: Mapped[str] = mapped_column(String(60), nullable=False)
    normalized: Mapped[str] = mapped_column(String(60), nullable=False)
    usage_count: Mapped[int] = mapped_column(Integer, default=0, server_default="0", nullable=False)
    color: Mapped[str | None] = mapped_column(String(7))
    pinned_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        UniqueConstraint("account_id", "normalized", name="tag_unique"),
        Index("tag_usage_idx", "account_id", usage_count.desc()),
    )


class Entry(Base, TimestampMixin):
    __tablename__ = "entry"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("app_user.id", ondelete="RESTRICT"), nullable=False
    )
    # SET NULL, not CASCADE: deleting the audio must not destroy the tasks drawn
    # from it (ADR-028).
    capture_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("capture.id", ondelete="SET NULL")
    )
    project_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("project.id", ondelete="SET NULL")
    )

    entry_type: Mapped[str] = mapped_column(String(16), nullable=False)
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    body: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(
        String(24), default=EntryStatus.ACTIVE, server_default="active", nullable=False
    )

    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    origin: Mapped[str] = mapped_column(
        String(16), default=EntryOrigin.AI, server_default="ai", nullable=False
    )
    ai_run_id: Mapped[uuid.UUID | None] = mapped_column(PgUUID(as_uuid=True))
    confidence: Mapped[float | None] = mapped_column(Numeric(4, 3))
    source_span_start: Mapped[int | None] = mapped_column(Integer)
    source_span_end: Mapped[int | None] = mapped_column(Integer)

    # Authoritative: a reprocessing run never overwrites a human correction
    # (ADR-027).
    edited_by_user_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Phase 2. Pinning is a user act, so it is a timestamp rather than a boolean:
    # "pinned, and since when" answers ordering questions a boolean cannot.
    pinned_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Phase 4. NULL means personal — the phase 1 behaviour, and still the
    # default. Making this mandatory would have forced every existing row into a
    # synthetic "default workspace": a rewrite of working data to satisfy a new
    # abstraction. The restrictive RLS policy of ADR-054 reads this column.
    workspace_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("workspace.id", ondelete="SET NULL")
    )

    # Maintained by PostgreSQL, not by the application (ADR-037). A trigger or an
    # application-side update would drift the moment one write path forgets it,
    # and a search index that is right 95 % of the time is worse than none.
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('french', coalesce(title, '')), 'A') || "
            "setweight(to_tsvector('french', coalesce(body, '')), 'B')",
            persisted=True,
        ),
    )

    version: Mapped[int] = mapped_column(Integer, default=1, server_default="1", nullable=False)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # `foreign_keys` is required, not decorative: `task` now carries a second FK
    # to `entry` (`recurred_from_entry_id`), and without this the ORM cannot tell
    # which one defines the relationship — it raises rather than guessing, which
    # is the right behaviour and the reason this argument exists.
    task: Mapped[Task | None] = relationship(
        back_populates="entry",
        cascade="all, delete-orphan",
        uselist=False,
        lazy="selectin",
        foreign_keys="Task.entry_id",
    )

    __table_args__ = (
        _enum_check("entry_type", EntryType),
        _enum_check("status", EntryStatus),
        _enum_check("origin", EntryOrigin),
        CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="confidence_range",
        ),
        CheckConstraint(
            "source_span_start IS NULL OR source_span_end > source_span_start",
            name="span_valid",
        ),
        Index(
            "entry_account_occurred_idx",
            "account_id",
            occurred_at.desc(),
            postgresql_where=deleted_at.is_(None),
        ),
        Index(
            "entry_account_type_idx",
            "account_id",
            "entry_type",
            occurred_at.desc(),
            postgresql_where=deleted_at.is_(None),
        ),
        Index(
            "entry_needs_review_idx",
            "account_id",
            "created_at",
            postgresql_where=status == "needs_review",
        ),
        Index("entry_sync_idx", "account_id", "updated_at", "id"),
        Index(
            "entry_search_idx",
            "search_vector",
            postgresql_using="gin",
            postgresql_where=deleted_at.is_(None),
        ),
        Index(
            "entry_pinned_idx",
            "account_id",
            pinned_at.desc(),
            postgresql_where=pinned_at.isnot(None),
        ),
    )


class Task(Base):
    __tablename__ = "task"

    entry_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("entry.id", ondelete="CASCADE"), primary_key=True
    )
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    due_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    due_precision: Mapped[str | None] = mapped_column(String(8))
    # The user's own wording, kept so a wrong resolution can be audited.
    due_raw_expression: Mapped[str | None] = mapped_column(String(120))
    priority: Mapped[str] = mapped_column(
        String(8), default=Priority.NORMAL, server_default="normal", nullable=False
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    snoozed_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    estimated_minutes: Mapped[int | None] = mapped_column(Integer)
    assignee_label: Mapped[str | None] = mapped_column(String(120))
    recurrence_rule: Mapped[str | None] = mapped_column(String(255))
    # How many occurrences of a recurring task have been completed. Feeds COUNT=
    # so "every Monday, 10 times" actually stops after ten.
    recurrence_count: Mapped[int] = mapped_column(
        Integer, default=0, server_default="0", nullable=False
    )
    # Set on the occurrence generated by completing the previous one, so the
    # timeline can distinguish "you created this" from "it came round again".
    recurred_from_entry_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("entry.id", ondelete="SET NULL")
    )
    # Ordering inside a manual list. Sparse, like subtask.position.
    position: Mapped[int | None] = mapped_column(Integer)
    external_ref: Mapped[dict[str, Any] | None] = mapped_column(JSONB)

    entry: Mapped[Entry] = relationship(back_populates="task", foreign_keys=[entry_id])

    __table_args__ = (
        _enum_check("priority", Priority),
        CheckConstraint(
            "due_precision IS NULL OR due_precision IN ('day','hour','minute')",
            name="due_precision_valid",
        ),
        Index(
            "task_due_idx",
            "due_at",
            postgresql_where=completed_at.is_(None) & due_at.isnot(None),
        ),
    )


class EntryTag(Base):
    __tablename__ = "entry_tag"

    entry_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("entry.id", ondelete="CASCADE"), primary_key=True
    )
    tag_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("tag.id", ondelete="CASCADE"), primary_key=True
    )
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    origin: Mapped[str] = mapped_column(
        String(8), default="ai", server_default="ai", nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (CheckConstraint("origin IN ('ai','user')", name="origin_valid"),)


class EntryLink(Base):
    __tablename__ = "entry_link"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    source_entry_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("entry.id", ondelete="CASCADE"), nullable=False
    )
    target_entry_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("entry.id", ondelete="CASCADE"), nullable=False
    )
    link_type: Mapped[str] = mapped_column(String(24), nullable=False)
    strength: Mapped[float | None] = mapped_column(Numeric(4, 3))
    origin: Mapped[str] = mapped_column(
        String(8), default="ai", server_default="ai", nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        CheckConstraint("source_entry_id <> target_entry_id", name="no_self_link"),
        CheckConstraint(
            "link_type IN ('derived_from','similar_to','blocks','follows_up',"
            "'contradicts','mentions','supersedes')",
            name="link_type_valid",
        ),
        UniqueConstraint(
            "source_entry_id", "target_entry_id", "link_type", name="entry_link_unique"
        ),
    )


# --------------------------------------------------------------------------- #
# Planning (Phase 2)
# --------------------------------------------------------------------------- #
class Subtask(Base, TimestampMixin):
    """A checklist item under a task.

    Deliberately *not* a nested `entry`. A subtask has no type, no confidence, no
    provenance, no tags — modelling it as an entry would mean every list query in
    the product has to remember to exclude children, and one that forgets shows
    the user their own checklist as top-level noise. One flat level only: two
    levels of nesting is a project, and projects already exist.
    """

    __tablename__ = "subtask"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    entry_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("entry.id", ondelete="CASCADE"), nullable=False
    )
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    # Sparse (10, 20, 30…) so a reorder rewrites one row instead of the whole
    # list. Renumbering happens only when two neighbours have no gap left.
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    origin: Mapped[str] = mapped_column(
        String(16), default=EntryOrigin.USER, server_default="user", nullable=False
    )

    __table_args__ = (
        _enum_check("origin", EntryOrigin),
        CheckConstraint("position >= 0", name="position_positive"),
        Index("subtask_entry_idx", "entry_id", "position"),
    )


class Reminder(Base, TimestampMixin):
    """A scheduled nudge about an entry.

    Separate from `task.due_at` on purpose: a due date is *when the work is
    owed*, a reminder is *when to be told*. Conflating them means you cannot be
    reminded twice, cannot be reminded the day before, and cannot dismiss the
    reminder without moving the deadline.
    """

    __tablename__ = "reminder"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("app_user.id", ondelete="CASCADE"), nullable=False
    )
    entry_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("entry.id", ondelete="CASCADE"))

    remind_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    channel: Mapped[str] = mapped_column(
        String(8), default=ReminderChannel.PUSH, server_default="push", nullable=False
    )
    status: Mapped[str] = mapped_column(
        String(12), default=ReminderStatus.SCHEDULED, server_default="scheduled", nullable=False
    )
    # The wording that generated it ("-15m", "la veille à 18h"), kept so the
    # interface can show the rule rather than a bare timestamp.
    offset_rule: Mapped[str | None] = mapped_column(String(32))
    title: Mapped[str | None] = mapped_column(String(200))
    body: Mapped[str | None] = mapped_column(String(500))

    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    attempts: Mapped[int] = mapped_column(
        SmallInteger, default=0, server_default="0", nullable=False
    )
    last_error: Mapped[str | None] = mapped_column(String(120))

    # Makes the dispatcher idempotent: re-running a batch cannot fire the same
    # reminder twice, whatever happens between the send and the status update.
    dedupe_key: Mapped[str] = mapped_column(String(120), nullable=False)

    __table_args__ = (
        _enum_check("channel", ReminderChannel),
        _enum_check("status", ReminderStatus),
        UniqueConstraint("account_id", "dedupe_key", name="reminder_dedupe_unique"),
        Index(
            "reminder_due_idx",
            "remind_at",
            postgresql_where=status == "scheduled",
        ),
        Index("reminder_entry_idx", "entry_id", "remind_at"),
    )


class Notification(Base):
    """An item in the in-app notification centre.

    Written whether or not a push went out, and written *before* the push is
    attempted. A notification the user can find in the app is the durable
    record; the push is a best-effort courtesy on top of it. Doing it the other
    way round loses the notification whenever the device is unreachable.
    """

    __tablename__ = "notification"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("app_user.id", ondelete="CASCADE"), nullable=False
    )
    entry_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("entry.id", ondelete="CASCADE"))
    capture_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("capture.id", ondelete="CASCADE")
    )
    reminder_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("reminder.id", ondelete="SET NULL")
    )

    kind: Mapped[str] = mapped_column(String(24), nullable=False)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    body: Mapped[str | None] = mapped_column(String(500))
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, server_default="{}", nullable=False)

    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    pushed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        _enum_check("kind", NotificationKind),
        Index(
            "notification_unread_idx",
            "user_id",
            created_at.desc(),
            postgresql_where=read_at.is_(None),
        ),
        Index("notification_user_time_idx", "user_id", created_at.desc()),
    )


class SavedFilter(Base, TimestampMixin):
    """A named query. The user's own vocabulary for their own work.

    Stores the *query string*, not a compiled predicate: the grammar of
    `domain.search_query` is the contract, and a saved filter written today keeps
    working when the parser gains a keyword tomorrow.
    """

    __tablename__ = "saved_filter"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("app_user.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(60), nullable=False)
    query: Mapped[str] = mapped_column(String(500), nullable=False)
    icon: Mapped[str | None] = mapped_column(String(40))
    color: Mapped[str | None] = mapped_column(String(7))
    position: Mapped[int] = mapped_column(Integer, default=0, server_default="0", nullable=False)
    pinned_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        UniqueConstraint("user_id", "name", name="saved_filter_name_unique"),
        Index("saved_filter_user_idx", "user_id", "position"),
    )


class ActivityEvent(Base):
    """The Timeline — what happened, in the user's terms.

    Three history tables now exist and they are not redundant:
    `audit_log` answers a security question, `correction_event` answers a model
    quality question, and this one answers "what happened to my task?". Merging
    them would force one vocabulary onto three audiences and serve none of them.
    """

    __tablename__ = "activity_event"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("app_user.id", ondelete="SET NULL")
    )
    entry_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("entry.id", ondelete="CASCADE"))
    capture_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("capture.id", ondelete="SET NULL")
    )
    project_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("project.id", ondelete="SET NULL")
    )

    action: Mapped[str] = mapped_column(String(24), nullable=False)
    # Denormalised so the timeline renders without joining to rows that may have
    # been deleted since. A history that disappears when its subject does is not
    # a history.
    subject_label: Mapped[str | None] = mapped_column(String(300))
    actor_type: Mapped[str] = mapped_column(
        String(16), default="user", server_default="user", nullable=False
    )
    detail: Mapped[dict[str, Any]] = mapped_column(JSONB, server_default="{}", nullable=False)
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        _enum_check("action", ActivityAction),
        CheckConstraint("actor_type IN ('user','ai','system')", name="actor_type_valid"),
        Index("activity_account_time_idx", "account_id", occurred_at.desc()),
        Index("activity_entry_idx", "entry_id", occurred_at.desc()),
    )


# --------------------------------------------------------------------------- #
# Intelligence
# --------------------------------------------------------------------------- #
class AiRun(Base):
    __tablename__ = "ai_run"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("account.id", ondelete="SET NULL")
    )
    capture_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("capture.id", ondelete="SET NULL")
    )
    prompt_name: Mapped[str | None] = mapped_column(String(64))
    prompt_version: Mapped[int | None] = mapped_column(Integer)

    operation: Mapped[str] = mapped_column(String(32), nullable=False)
    model_id: Mapped[str] = mapped_column(String(64), nullable=False)
    provider: Mapped[str] = mapped_column(String(24), nullable=False)
    status: Mapped[str] = mapped_column(String(16), nullable=False)

    input_tokens: Mapped[int | None] = mapped_column(Integer)
    output_tokens: Mapped[int | None] = mapped_column(Integer)
    cache_read_tokens: Mapped[int | None] = mapped_column(Integer)
    cache_write_tokens: Mapped[int | None] = mapped_column(Integer)
    cost_micro_eur: Mapped[int | None] = mapped_column(BigInteger)
    latency_ms: Mapped[int | None] = mapped_column(Integer)

    # No content, ever: not the rendered prompt, not the response (AI.md §10.2).
    error_code: Mapped[str | None] = mapped_column(String(48))
    retry_count: Mapped[int] = mapped_column(
        SmallInteger, default=0, server_default="0", nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        _enum_check("operation", AiOperation),
        _enum_check("status", AiRunStatus),
    )


class CorrectionEvent(Base):
    __tablename__ = "correction_event"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    entry_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("entry.id", ondelete="CASCADE"), nullable=False
    )
    ai_run_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("ai_run.id", ondelete="SET NULL")
    )
    field: Mapped[str] = mapped_column(String(48), nullable=False)
    old_value: Mapped[str | None] = mapped_column(Text)
    new_value: Mapped[str | None] = mapped_column(Text)
    corrected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


# --------------------------------------------------------------------------- #
# Billing (quota enforcement only in Phase 1)
# --------------------------------------------------------------------------- #
class Plan(Base):
    __tablename__ = "plan"

    code: Mapped[str] = mapped_column(String(24), primary_key=True)
    display_name: Mapped[str] = mapped_column(String(60), nullable=False)
    price_cents_month: Mapped[int] = mapped_column(Integer, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), default="EUR", nullable=False)
    max_quick_captures_month: Mapped[int | None] = mapped_column(Integer)
    max_meeting_minutes_month: Mapped[int | None] = mapped_column(Integer)
    max_capture_duration_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    history_retention_days: Mapped[int | None] = mapped_column(Integer)
    features: Mapped[dict[str, Any]] = mapped_column(JSONB, server_default="{}", nullable=False)


class Subscription(Base, TimestampMixin):
    __tablename__ = "subscription"

    id: Mapped[uuid.UUID] = uuid_pk()
    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), unique=True, nullable=False
    )
    plan_code: Mapped[str] = mapped_column(
        ForeignKey("plan.code", ondelete="RESTRICT"), nullable=False
    )
    status: Mapped[str] = mapped_column(
        String(24), default="active", server_default="active", nullable=False
    )
    seats: Mapped[int] = mapped_column(SmallInteger, default=1, server_default="1", nullable=False)
    current_period_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    current_period_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class UsageCounter(Base):
    __tablename__ = "usage_counter"

    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), primary_key=True
    )
    metric: Mapped[str] = mapped_column(String(32), primary_key=True)
    period_start: Mapped[datetime] = mapped_column(Date, primary_key=True)
    value: Mapped[int] = mapped_column(BigInteger, default=0, server_default="0", nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


# --------------------------------------------------------------------------- #
# Platform
# --------------------------------------------------------------------------- #
class Outbox(Base):
    """Transactional outbox (ADR-010): the event is written in the same
    transaction as the business change, so it cannot be lost."""

    __tablename__ = "outbox"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    account_id: Mapped[uuid.UUID | None] = mapped_column(PgUUID(as_uuid=True))
    event_type: Mapped[str] = mapped_column(String(64), nullable=False)
    aggregate_type: Mapped[str] = mapped_column(String(48), nullable=False)
    aggregate_id: Mapped[uuid.UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    trace_id: Mapped[str | None] = mapped_column(String(64))
    status: Mapped[str] = mapped_column(String(16), default="pending", nullable=False)
    attempts: Mapped[int] = mapped_column(
        SmallInteger, default=0, server_default="0", nullable=False
    )
    available_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    dispatched_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        CheckConstraint("status IN ('pending','dispatched','failed')", name="status_valid"),
        Index("outbox_pending_idx", "available_at", postgresql_where=status == "pending"),
    )


class JobRun(Base):
    __tablename__ = "job_run"

    id: Mapped[uuid.UUID] = uuid_pk()
    job_name: Mapped[str] = mapped_column(String(64), nullable=False)
    account_id: Mapped[uuid.UUID | None] = mapped_column(PgUUID(as_uuid=True))
    aggregate_id: Mapped[uuid.UUID | None] = mapped_column(PgUUID(as_uuid=True))
    queue: Mapped[str] = mapped_column(String(32), nullable=False)
    status: Mapped[str] = mapped_column(String(16), nullable=False)
    attempt: Mapped[int] = mapped_column(
        SmallInteger, default=1, server_default="1", nullable=False
    )
    error_code: Mapped[str | None] = mapped_column(String(48))
    trace_id: Mapped[str | None] = mapped_column(String(64))
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('queued','running','succeeded','failed','dead')", name="status_valid"
        ),
    )


class AuditLog(Base):
    __tablename__ = "audit_log"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    account_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("account.id", ondelete="SET NULL")
    )
    actor_user_id: Mapped[uuid.UUID | None] = mapped_column(PgUUID(as_uuid=True))
    actor_type: Mapped[str] = mapped_column(String(16), nullable=False)
    action: Mapped[str] = mapped_column(String(64), nullable=False)
    resource_type: Mapped[str | None] = mapped_column(String(48))
    resource_id: Mapped[uuid.UUID | None] = mapped_column(PgUUID(as_uuid=True))
    metadata_: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, server_default="{}", nullable=False
    )
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        CheckConstraint(
            "actor_type IN ('user','system','admin','integration')", name="actor_type_valid"
        ),
    )


# Tables carrying tenant data — the RLS migration and the isolation test both
# iterate over this list, so adding a table without a policy is caught by tests.
TENANT_TABLES: tuple[str, ...] = (
    "app_user",
    "device",
    "capture",
    "transcript",
    "transcript_segment",
    "project",
    "tag",
    "entry",
    "task",
    "entry_tag",
    "entry_link",
    "correction_event",
    "subscription",
    "usage_counter",
    # Phase 2
    "subtask",
    "reminder",
    "notification",
    "saved_filter",
    "activity_event",
    # Phase 3. Defined in `app.infra.db.models.ai`, listed here because this
    # tuple is the single list the RLS migration and the isolation test both
    # walk — splitting it would let a table be added to one and not the other.
    "chunk",
    "entity",
    "entity_mention",
    "conversation",
    "conversation_message",
    "memory",
    "digest",
    # Phase 4. Defined in `app.infra.db.models.enterprise`, listed here because
    # this tuple is the single list the RLS migrations and the isolation test
    # both walk.
    "workspace",
    "workspace_member",
    "invitation",
    "comment",
    "mention",
    "share_link",
    "integration_connection",
    "external_link",
    "meeting_session",
)
