"""Planning, reminders, notifications and history (Phase 2)

Adds the five tables phase 2 needs — `subtask`, `reminder`, `notification`,
`saved_filter`, `activity_event` — plus the columns that make advanced task
management, full-text search and push delivery possible.

Three things here are not mechanical and deserve a note:

* `entry.search_vector` is a **generated column**, maintained by PostgreSQL
  (ADR-037). A trigger or an application-side update would drift the first time
  a write path forgets it, and a search index that is right most of the time is
  worse than no search at all.

* `device.install_id` is added NOT NULL to a table that may already hold rows,
  so it goes in as expand-contract: nullable, backfilled, then constrained.
  Adding it NOT NULL in one statement works on an empty table and fails in
  production, which is the worst possible place to find out.

* The five new tables carry tenant data, so they get RLS policies **in the same
  migration that creates them**. A table that exists for even one deploy without
  a policy is a table that leaks for one deploy.

Revision ID: 0005
Revises: 0004
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Kept in sync with app.infra.db.models.core.TENANT_TABLES; the isolation test
# compares the two and fails if a table is added without a policy.
NEW_TENANT_TABLES: tuple[str, ...] = (
    "subtask",
    "reminder",
    "notification",
    "saved_filter",
    "activity_event",
)

# Columns that were `timestamp without time zone` before this migration. The two
# created here (`notification.created_at`, `activity_event.occurred_at`) are in
# the list too: they are created by the autogenerated block above and converted
# in the same pass, so the schema ends up uniform rather than half-and-half.
NAIVE_TIMESTAMP_COLUMNS: tuple[tuple[str, str], ...] = (
    ("account", "created_at"),
    ("account", "updated_at"),
    ("activity_event", "occurred_at"),
    ("ai_run", "created_at"),
    ("app_user", "created_at"),
    ("app_user", "updated_at"),
    ("audit_log", "occurred_at"),
    ("capture", "created_at"),
    ("capture", "updated_at"),
    ("correction_event", "corrected_at"),
    ("device", "created_at"),
    ("device", "updated_at"),
    ("entry", "created_at"),
    ("entry", "updated_at"),
    ("entry_link", "created_at"),
    ("entry_tag", "created_at"),
    ("job_run", "created_at"),
    ("notification", "created_at"),
    ("outbox", "created_at"),
    ("project", "created_at"),
    ("project", "updated_at"),
    ("reminder", "created_at"),
    ("reminder", "updated_at"),
    ("saved_filter", "created_at"),
    ("saved_filter", "updated_at"),
    ("subscription", "created_at"),
    ("subscription", "updated_at"),
    ("subtask", "created_at"),
    ("subtask", "updated_at"),
    ("tag", "created_at"),
    ("transcript", "created_at"),
    ("usage_counter", "updated_at"),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_filter",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("query", sa.String(length=500), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("saved_filter_account_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("saved_filter_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("saved_filter_pkey")),
        sa.UniqueConstraint("user_id", "name", name="saved_filter_name_unique"),
    )
    op.create_index("saved_filter_user_idx", "saved_filter", ["user_id", "position"], unique=False)
    op.create_table(
        "activity_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("entry_id", sa.UUID(), nullable=True),
        sa.Column("capture_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("subject_label", sa.String(length=300), nullable=True),
        sa.Column("actor_type", sa.String(length=16), server_default="user", nullable=False),
        sa.Column(
            "detail", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("occurred_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "action IN ('created', 'edited', 'completed', 'reopened', 'archived', 'deleted', 'restored', 'snoozed', 'rescheduled', 'priority_changed', 'project_changed', 'tagged', 'untagged', 'subtask_added', 'subtask_completed', 'reminder_set', 'reminder_fired', 'recurred', 'captured')",
            name=op.f("activity_event_action_valid"),
        ),
        sa.CheckConstraint(
            "actor_type IN ('user','ai','system')", name=op.f("activity_event_actor_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("activity_event_account_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["capture.id"],
            name=op.f("activity_event_capture_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["entry.id"],
            name=op.f("activity_event_entry_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("activity_event_project_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("activity_event_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("activity_event_pkey")),
    )
    op.create_index(
        "activity_account_time_idx",
        "activity_event",
        ["account_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "activity_entry_idx",
        "activity_event",
        ["entry_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_table(
        "reminder",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=True),
        sa.Column("remind_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel", sa.String(length=8), server_default="push", nullable=False),
        sa.Column("status", sa.String(length=12), server_default="scheduled", nullable=False),
        sa.Column("offset_rule", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("body", sa.String(length=500), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=120), nullable=True),
        sa.Column("dedupe_key", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "channel IN ('push', 'local', 'email')", name=op.f("reminder_channel_valid")
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'sent', 'failed', 'cancelled', 'dismissed')",
            name=op.f("reminder_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("reminder_account_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["entry.id"], name=op.f("reminder_entry_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("reminder_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("reminder_pkey")),
        sa.UniqueConstraint("account_id", "dedupe_key", name="reminder_dedupe_unique"),
    )
    op.create_index(
        "reminder_due_idx",
        "reminder",
        ["remind_at"],
        unique=False,
        postgresql_where=sa.text("status = 'scheduled'"),
    )
    op.create_index("reminder_entry_idx", "reminder", ["entry_id", "remind_at"], unique=False)
    op.create_table(
        "subtask",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("origin", sa.String(length=16), server_default="user", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "origin IN ('ai', 'user', 'integration', 'transform')",
            name=op.f("subtask_origin_valid"),
        ),
        sa.CheckConstraint("position >= 0", name=op.f("subtask_position_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["account.id"], name=op.f("subtask_account_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["entry.id"], name=op.f("subtask_entry_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("subtask_pkey")),
    )
    op.create_index("subtask_entry_idx", "subtask", ["entry_id", "position"], unique=False)
    op.create_table(
        "notification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=True),
        sa.Column("capture_id", sa.UUID(), nullable=True),
        sa.Column("reminder_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.String(length=500), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('reminder', 'due_soon', 'overdue', 'capture_ready', 'capture_failed', 'review_pending', 'digest', 'system')",
            name=op.f("notification_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("notification_account_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["capture.id"],
            name=op.f("notification_capture_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["entry.id"], name=op.f("notification_entry_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["reminder.id"],
            name=op.f("notification_reminder_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("notification_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("notification_pkey")),
    )
    op.create_index(
        "notification_unread_idx",
        "notification",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_index(
        "notification_user_time_idx",
        "notification",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # Expand-contract: the column is added nullable, backfilled from the row's
    # own id (an existing device has no install id and never will), then
    # constrained. One statement would fail on any table with rows in it.
    op.add_column("device", sa.Column("install_id", sa.String(length=64), nullable=True))
    op.execute("UPDATE device SET install_id = id::text WHERE install_id IS NULL")
    op.alter_column("device", "install_id", nullable=False)
    op.add_column(
        "device",
        sa.Column("push_provider", sa.String(length=8), server_default="none", nullable=False),
    )
    op.add_column(
        "device", sa.Column("push_token_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("device", sa.Column("push_failed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "device",
        sa.Column("push_failure_count", sa.SmallInteger(), server_default="0", nullable=False),
    )
    op.add_column("device", sa.Column("name", sa.String(length=80), nullable=True))
    op.create_unique_constraint("device_install_unique", "device", ["user_id", "install_id"])
    op.create_index(
        "device_push_idx",
        "device",
        ["account_id", "push_provider"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.add_column("entry", sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "entry",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('french', coalesce(title, '')), 'A') || setweight(to_tsvector('french', coalesce(body, '')), 'B')",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "entry_pinned_idx",
        "entry",
        ["account_id", sa.literal_column("pinned_at DESC")],
        unique=False,
        postgresql_where=sa.text("pinned_at IS NOT NULL"),
    )
    op.create_index(
        "entry_search_idx",
        "entry",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.add_column("project", sa.Column("icon", sa.String(length=40), nullable=True))
    op.add_column("project", sa.Column("description", sa.String(length=500), nullable=True))
    op.add_column(
        "project", sa.Column("position", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("project", sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tag", sa.Column("color", sa.String(length=7), nullable=True))
    op.add_column("tag", sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        "tag_usage_idx", "tag", ["account_id", sa.literal_column("usage_count DESC")], unique=False
    )
    op.add_column(
        "task", sa.Column("recurrence_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("task", sa.Column("recurred_from_entry_id", sa.UUID(), nullable=True))
    op.add_column("task", sa.Column("position", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("task_recurred_from_entry_id_fkey"),
        "task",
        "entry",
        ["recurred_from_entry_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # Autogenerate does not diff CHECK constraints, so the widened platform set
    # and the new push_provider set are written by hand. Without this the
    # desktop clients phase 2 adds would be rejected by the database.
    op.drop_constraint(op.f("device_platform_valid"), "device", type_="check")
    op.create_check_constraint(
        op.f("device_platform_valid"),
        "device",
        "platform IN ('ios','android','web','watchos','wearos','windows','macos','linux')",
    )
    op.create_check_constraint(
        op.f("device_push_provider_valid"),
        "device",
        "push_provider IN ('fcm','wns','local','none')",
    )

    # -- Timestamps become timezone-aware (ADR-041) ---------------------------
    # `created_at` and friends were `timestamp without time zone`, which compares
    # as *local time*. Filtering one against an aware datetime raises at the
    # driver, and grouping one by day in a report silently answers with the UTC
    # offset applied — a statistics page that is wrong by an hour or a day.
    #
    # The USING clause is what makes the conversion correct rather than merely
    # accepted: the stored values were written by `now()` under a UTC session, so
    # they are reinterpreted as UTC instead of as the server's local time.
    for table, column in NAIVE_TIMESTAMP_COLUMNS:
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN {column} TYPE timestamptz "
            f"USING {column} AT TIME ZONE 'UTC'"
        )

    # -- Row Level Security for the new tenant tables (ADR-005) ---------------
    for table in NEW_TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
                USING (account_id = current_account_id())
                WITH CHECK (account_id = current_account_id())
            """
        )


def downgrade() -> None:
    for table, column in reversed(NAIVE_TIMESTAMP_COLUMNS):
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN {column} TYPE timestamp "
            f"USING {column} AT TIME ZONE 'UTC'"
        )

    for table in reversed(NEW_TENANT_TABLES):
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    op.drop_constraint(op.f("device_push_provider_valid"), "device", type_="check")
    op.drop_constraint(op.f("device_platform_valid"), "device", type_="check")
    op.create_check_constraint(
        op.f("device_platform_valid"),
        "device",
        "platform IN ('ios','android','web','watchos','wearos')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("task_recurred_from_entry_id_fkey"), "task", type_="foreignkey")
    op.drop_column("task", "position")
    op.drop_column("task", "recurred_from_entry_id")
    op.drop_column("task", "recurrence_count")
    op.drop_index("tag_usage_idx", table_name="tag")
    op.drop_column("tag", "pinned_at")
    op.drop_column("tag", "color")
    op.drop_column("project", "pinned_at")
    op.drop_column("project", "position")
    op.drop_column("project", "description")
    op.drop_column("project", "icon")
    op.drop_index(
        "entry_search_idx",
        table_name="entry",
        postgresql_using="gin",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "entry_pinned_idx", table_name="entry", postgresql_where=sa.text("pinned_at IS NOT NULL")
    )
    op.drop_column("entry", "search_vector")
    op.drop_column("entry", "pinned_at")
    op.drop_index(
        "device_push_idx", table_name="device", postgresql_where=sa.text("revoked_at IS NULL")
    )
    op.drop_constraint("device_install_unique", "device", type_="unique")
    op.drop_column("device", "name")
    op.drop_column("device", "push_failure_count")
    op.drop_column("device", "push_failed_at")
    op.drop_column("device", "push_token_updated_at")
    op.drop_column("device", "push_provider")
    op.drop_column("device", "install_id")
    op.drop_index("notification_user_time_idx", table_name="notification")
    op.drop_index(
        "notification_unread_idx",
        table_name="notification",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_table("notification")
    op.drop_index("subtask_entry_idx", table_name="subtask")
    op.drop_table("subtask")
    op.drop_index("reminder_entry_idx", table_name="reminder")
    op.drop_index(
        "reminder_due_idx", table_name="reminder", postgresql_where=sa.text("status = 'scheduled'")
    )
    op.drop_table("reminder")
    op.drop_index("activity_entry_idx", table_name="activity_event")
    op.drop_index("activity_account_time_idx", table_name="activity_event")
    op.drop_table("activity_event")
    op.drop_index("saved_filter_user_idx", table_name="saved_filter")
    op.drop_table("saved_filter")
    # ### end Alembic commands ###
