"""initial schema

Revision ID: 5b446b2499ed
Revises: 
Create Date: 2026-07-27 22:25:46.059842+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5b446b2499ed'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('prompt_path', sa.String(length=512), nullable=False),
    sa.Column('prompt_sha256', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'succeeded', 'failed')", name=op.f('ck_agent_run_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_run'))
    )
    op.create_table('deliverable_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_publication', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliverable_type')),
    sa.UniqueConstraint('code', name=op.f('uq_deliverable_type_code'))
    )
    op.create_table('phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phase')),
    sa.UniqueConstraint('code', name=op.f('uq_phase_code')),
    sa.UniqueConstraint('ordinal', name='uq_phase_ordinal')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('based_in', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile')),
    sa.UniqueConstraint('code', name=op.f('uq_profile_code'))
    )
    op.create_table('review_criterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_criterion')),
    sa.UniqueConstraint('code', name=op.f('uq_review_criterion_code'))
    )
    op.create_table('skill_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_domain')),
    sa.UniqueConstraint('code', name=op.f('uq_skill_domain_code'))
    )
    op.create_table('skill_level',
    sa.Column('level', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('evidence_expectation', sa.Text(), nullable=True),
    sa.CheckConstraint("level IN ('0', '1', '2', '3', '4', '5')", name=op.f('ck_skill_level_level_range')),
    sa.PrimaryKeyConstraint('level', name=op.f('pk_skill_level')),
    sa.UniqueConstraint('code', name=op.f('uq_skill_level_code'))
    )
    op.create_table('target_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_role')),
    sa.UniqueConstraint('code', name=op.f('uq_target_role_code'))
    )
    op.create_table('business_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_context', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('symptom', sa.Text(), nullable=False),
    sa.Column('claimed_annual_loss', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'quantified', 'reviewed', 'archived')", name=op.f('ck_business_case_status')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_business_case_profile_id_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_case'))
    )
    op.create_table('deliverable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('artifact_url', sa.String(length=1024), nullable=True),
    sa.Column('artifact_path', sa.String(length=1024), nullable=True),
    sa.Column('business_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status <> 'published' OR published_on IS NOT NULL", name=op.f('ck_deliverable_published_requires_date')),
    sa.CheckConstraint("status IN ('planned', 'in_progress', 'published', 'abandoned')", name=op.f('ck_deliverable_status')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_deliverable_profile_id_profile'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['deliverable_type.id'], name=op.f('fk_deliverable_type_id_deliverable_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliverable'))
    )
    op.create_table('deliverable_quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('deliverable_type_id', sa.Integer(), nullable=False),
    sa.Column('min_per_quarter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_type_id'], ['deliverable_type.id'], name=op.f('fk_deliverable_quota_deliverable_type_id_deliverable_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['phase_id'], ['phase.id'], name=op.f('fk_deliverable_quota_phase_id_phase'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliverable_quota')),
    sa.UniqueConstraint('phase_id', 'deliverable_type_id', name='uq_quota_phase_type')
    )
    op.create_table('job_posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_role_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('seniority_label', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('posted_on', sa.Date(), nullable=True),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_role.id'], name=op.f('fk_job_posting_target_role_id_target_role'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_posting'))
    )
    op.create_table('periodic_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('weekly', 'quarterly')", name=op.f('ck_periodic_review_kind')),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_periodic_review_period_order')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.id'], name=op.f('fk_periodic_review_agent_run_id_agent_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_periodic_review_profile_id_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_periodic_review')),
    sa.UniqueConstraint('profile_id', 'kind', 'period_start', name='uq_periodic_review')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('decay_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['skill_domain.id'], name=op.f('fk_skill_domain_id_skill_domain'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill')),
    sa.UniqueConstraint('code', name=op.f('uq_skill_code'))
    )
    op.create_table('assumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('base_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('low_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('high_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("confidence IN ('low', 'medium', 'high')", name=op.f('ck_assumption_confidence')),
    sa.CheckConstraint('high_value IS NULL OR high_value >= base_value', name=op.f('ck_assumption_high_above_base')),
    sa.CheckConstraint('low_value IS NULL OR low_value <= base_value', name=op.f('ck_assumption_low_below_base')),
    sa.ForeignKeyConstraint(['case_id'], ['business_case.id'], name=op.f('fk_assumption_case_id_business_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assumption')),
    sa.UniqueConstraint('case_id', 'code', name='uq_assumption_case_code')
    )
    op.create_table('cause_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['business_case.id'], name=op.f('fk_cause_node_case_id_business_case'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['cause_node.id'], name=op.f('fk_cause_node_parent_id_cause_node'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cause_node'))
    )
    op.create_table('deliverable_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('measured_on', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverable.id'], name=op.f('fk_deliverable_impact_deliverable_id_deliverable'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliverable_impact')),
    sa.UniqueConstraint('deliverable_id', 'metric_code', 'measured_on', name='uq_impact_point')
    )
    op.create_table('deliverable_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('contribution', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("contribution IN ('1', '2', '3')", name=op.f('ck_deliverable_skill_contribution_range')),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverable.id'], name=op.f('fk_deliverable_skill_deliverable_id_deliverable'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_deliverable_skill_skill_id_skill'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliverable_skill')),
    sa.UniqueConstraint('deliverable_id', 'skill_id', name='uq_deliverable_skill')
    )
    op.create_table('job_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('raw_label', sa.String(length=255), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.Column('importance', sa.String(length=32), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("importance IN ('must_have', 'nice_to_have')", name=op.f('ck_job_requirement_importance')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.id'], name=op.f('fk_job_requirement_agent_run_id_agent_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['posting_id'], ['job_posting.id'], name=op.f('fk_job_requirement_posting_id_job_posting'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_job_requirement_skill_id_skill'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_requirement')),
    sa.UniqueConstraint('posting_id', 'raw_label', 'agent_run_id', name='uq_requirement')
    )
    op.create_table('mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverable.id'], name=op.f('fk_mention_deliverable_id_deliverable'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_mention_profile_id_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mention'))
    )
    op.create_table('roi_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('discount_rate >= 0', name=op.f('ck_roi_model_discount_rate_non_negative')),
    sa.CheckConstraint('horizon_years BETWEEN 1 AND 15', name=op.f('ck_roi_model_horizon_range')),
    sa.ForeignKeyConstraint(['case_id'], ['business_case.id'], name=op.f('fk_roi_model_case_id_business_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roi_model')),
    sa.UniqueConstraint('case_id', 'version', name='uq_roi_model_case_version')
    )
    op.create_table('skill_edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_skill_id', sa.Integer(), nullable=False),
    sa.Column('dependent_skill_id', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("required_level IN ('0', '1', '2', '3', '4', '5')", name=op.f('ck_skill_edge_required_level_range')),
    sa.CheckConstraint('prerequisite_skill_id <> dependent_skill_id', name=op.f('ck_skill_edge_no_self_dependency')),
    sa.ForeignKeyConstraint(['dependent_skill_id'], ['skill.id'], name=op.f('fk_skill_edge_dependent_skill_id_skill'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_skill_id'], ['skill.id'], name=op.f('fk_skill_edge_prerequisite_skill_id_skill'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_edge')),
    sa.UniqueConstraint('prerequisite_skill_id', 'dependent_skill_id', name='uq_skill_edge')
    )
    op.create_table('skill_level_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('from_level', sa.Integer(), nullable=False),
    sa.Column('to_level', sa.Integer(), nullable=False),
    sa.Column('changed_on', sa.Date(), nullable=False),
    sa.Column('deliverable_id', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("from_level IN ('0', '1', '2', '3', '4', '5')", name=op.f('ck_skill_level_change_from_level_range')),
    sa.CheckConstraint("to_level IN ('0', '1', '2', '3', '4', '5')", name=op.f('ck_skill_level_change_to_level_range')),
    sa.CheckConstraint('to_level <= from_level OR deliverable_id IS NOT NULL', name=op.f('ck_skill_level_change_promotion_needs_evidence')),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverable.id'], name=op.f('fk_skill_level_change_deliverable_id_deliverable'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_skill_level_change_profile_id_profile'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_skill_level_change_skill_id_skill'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_level_change'))
    )
    op.create_table('skill_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('last_practised_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("current_level IN ('0', '1', '2', '3', '4', '5')", name=op.f('ck_skill_state_current_level_range')),
    sa.CheckConstraint("target_level IN ('0', '1', '2', '3', '4', '5')", name=op.f('ck_skill_state_target_level_range')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_skill_state_profile_id_profile'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_skill_state_skill_id_skill'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_state')),
    sa.UniqueConstraint('profile_id', 'skill_id', name='uq_skill_state_profile_skill')
    )
    op.create_table('solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('data_requirements', sa.Text(), nullable=True),
    sa.Column('architecture', sa.Text(), nullable=True),
    sa.Column('ai_component', sa.Text(), nullable=True),
    sa.Column('automation_component', sa.Text(), nullable=True),
    sa.Column('process_change', sa.Text(), nullable=True),
    sa.Column('governance', sa.Text(), nullable=True),
    sa.Column('deployment_plan', sa.Text(), nullable=True),
    sa.Column('key_risks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['business_case.id'], name=op.f('fk_solution_case_id_business_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solution')),
    sa.UniqueConstraint('case_id', name=op.f('uq_solution_case_id'))
    )
    op.create_table('case_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('roi_model_id', sa.Integer(), nullable=True),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_on', sa.Date(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('overall_score BETWEEN 0 AND 10', name=op.f('ck_case_review_overall_score_range')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.id'], name=op.f('fk_case_review_agent_run_id_agent_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['business_case.id'], name=op.f('fk_case_review_case_id_business_case'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roi_model_id'], ['roi_model.id'], name=op.f('fk_case_review_roi_model_id_roi_model'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_review'))
    )
    op.create_table('cause_driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cause_node_id', sa.Integer(), nullable=False),
    sa.Column('assumption_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['assumption.id'], name=op.f('fk_cause_driver_assumption_id_assumption'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cause_node_id'], ['cause_node.id'], name=op.f('fk_cause_driver_cause_node_id_cause_node'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cause_driver')),
    sa.UniqueConstraint('cause_node_id', 'assumption_id', name='uq_cause_driver')
    )
    op.create_table('roi_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roi_model_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('year_index', sa.Integer(), nullable=False),
    sa.Column('amount_assumption_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('build', 'run', 'license', 'change_management', 'hardware', 'labour_saving', 'loss_avoidance', 'revenue_uplift', 'working_capital')", name=op.f('ck_roi_line_category')),
    sa.CheckConstraint("kind IN ('cost', 'benefit')", name=op.f('ck_roi_line_kind')),
    sa.CheckConstraint('year_index >= 0', name=op.f('ck_roi_line_year_index_non_negative')),
    sa.ForeignKeyConstraint(['amount_assumption_id'], ['assumption.id'], name=op.f('fk_roi_line_amount_assumption_id_assumption'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['roi_model_id'], ['roi_model.id'], name=op.f('fk_roi_line_roi_model_id_roi_model'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roi_line'))
    )
    op.create_table('solution_kpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('baseline_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('measurement_frequency', sa.String(length=64), nullable=True),
    sa.Column('data_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solution.id'], name=op.f('fk_solution_kpi_solution_id_solution'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solution_kpi'))
    )
    op.create_table('case_review_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('target_assumption_id', sa.Integer(), nullable=True),
    sa.Column('target_area', sa.String(length=255), nullable=True),
    sa.Column('challenge', sa.Text(), nullable=False),
    sa.Column('evidence_demanded', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('resolved_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("persona IN ('cfo', 'coo', 'cio')", name=op.f('ck_case_review_challenge_persona')),
    sa.CheckConstraint("severity IN ('blocking', 'major', 'minor')", name=op.f('ck_case_review_challenge_severity')),
    sa.ForeignKeyConstraint(['review_id'], ['case_review.id'], name=op.f('fk_case_review_challenge_review_id_case_review'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_assumption_id'], ['assumption.id'], name=op.f('fk_case_review_challenge_target_assumption_id_assumption'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_review_challenge'))
    )
    op.create_table('case_review_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score BETWEEN 0 AND 10', name=op.f('ck_case_review_score_score_range')),
    sa.ForeignKeyConstraint(['criterion_id'], ['review_criterion.id'], name=op.f('fk_case_review_score_criterion_id_review_criterion'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['case_review.id'], name=op.f('fk_case_review_score_review_id_case_review'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_review_score')),
    sa.UniqueConstraint('review_id', 'criterion_id', name='uq_review_criterion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_review_score')
    op.drop_table('case_review_challenge')
    op.drop_table('solution_kpi')
    op.drop_table('roi_line')
    op.drop_table('cause_driver')
    op.drop_table('case_review')
    op.drop_table('solution')
    op.drop_table('skill_state')
    op.drop_table('skill_level_change')
    op.drop_table('skill_edge')
    op.drop_table('roi_model')
    op.drop_table('mention')
    op.drop_table('job_requirement')
    op.drop_table('deliverable_skill')
    op.drop_table('deliverable_impact')
    op.drop_table('cause_node')
    op.drop_table('assumption')
    op.drop_table('skill')
    op.drop_table('periodic_review')
    op.drop_table('job_posting')
    op.drop_table('deliverable_quota')
    op.drop_table('deliverable')
    op.drop_table('business_case')
    op.drop_table('target_role')
    op.drop_table('skill_level')
    op.drop_table('skill_domain')
    op.drop_table('review_criterion')
    op.drop_table('profile')
    op.drop_table('phase')
    op.drop_table('deliverable_type')
    op.drop_table('agent_run')
    # ### end Alembic commands ###
